#core:
#  defaultRuleSyntax: v2

log:
  level: INFO

api:
  insecure: true
  dashboard: true

accessLog: {}

metrics:
  prometheus:
    entryPoint: metrics
    buckets:
      - 0.1
      - 0.3
      - 1.2
      - 5.0
    addEntryPointsLabels: true
    addServicesLabels: true

entryPoints:
  # dashboard:
  #   address: :8080
  http:
    address: :80
    http:
      redirections:
        entryPoint:
          to: https
          scheme: https
  https:
    address: :443
    http:
      middlewares:
        - redirect-tls-mw@file
        - common-sec-mw@file
        - compress-mw@file
    http2:
      maxConcurrentStreams: 500

  metrics:
    address: :8088

providers:
  providersThrottleDuration: 2s
  file:
    directory: /dynamic
    watch: true
  docker:
    watch: true
    exposedByDefault: false
    endpoint: unix:///var/run/docker.sock

certificatesResolvers:
  default:
    acme:
      email: mathieu@pequin.fr
      storage: acme.json
      httpChallenge:
        entryPoint: http
