#core:
#  defaultRuleSyntax: v2

log:
  level: "INFO"
  filePath: "/var/log/traefik/traefik.log"
accessLog:
  filePath: "/var/log/traefik/access.log"
  format: json
#  filters:
#    statusCodes:
#      #- "200"
#      - "400-599"
  # collect logs as in-memory buffer before writing into log file
  bufferingSize: 0
  fields:
    headers:
      defaultMode: drop # drop all headers per default
      names:
          User-Agent: keep # log user agent strings

api:
  insecure: true
  dashboard: true

metrics:
  influxDB2:
    address: http://192.168.2.46:8086
    token: ZAL6j16obNWJ6h2OxxWYsYreEFPkGOUcX2hjs4i8_R_RdOd8ktQnyFflmXIVY5yLVqVmCT3ZZbDpZaXMd5146A==
    org: M3te0r
    bucket: traefik
    addEntryPointsLabels: true
    addRoutersLabels: true
    addServicesLabels: true
    pushInterval: 10s
  prometheus:
    entryPoint: metrics
    buckets:
      - 0.1
      - 0.3
      - 1.2
      - 5.0
    addEntryPointsLabels: true
    addRoutersLabels: true
    addServicesLabels: true
    headerLabels:
      useragent: User-Agent

entryPoints:
  # dashboard:
  #   address: :8080
  http:
    address: :80
    http:
      middlewares:
        - crowdsec-bouncer@file
      redirections:
        entryPoint:
          to: https
          scheme: https
  https:
    address: :443
    http:
      tls:
        certResolver: default
        domains:
          - main: "mete0r.fr"
            sans:
              - "*.mete0r.fr"
      middlewares:
        - crowdsec-bouncer@file
        - redirect-tls-mw@file
        - common-sec-mw@file
        - compress-mw@file
    http2:
      maxConcurrentStreams: 1000

  metrics:
    address: :8088

providers:
  providersThrottleDuration: 2s
  file:
    directory: /dynamic
    watch: true
  docker:
    watch: true
    exposedByDefault: false
    endpoint: unix:///var/run/docker.sock

certificatesResolvers:
  default:
    acme:
      email: mathieu@pequin.fr
      storage: acme.json
      dnsChallenge:
        provider: cloudflare
        #disablePropagationCheck: true # uncomment this if you have issues pulling certificates through cloudflare, By setting this flag to true disables the need to wait for the propagation of the TXT record to all authoritative name servers.
        resolvers:
          - "1.1.1.1:53"
          - "1.0.0.1:53"
