
version: '3'
services:
  transmission:
    image: haugene/transmission-openvpn
    container_name: transmission
    restart: unless-stopped
    networks:
      - traefik-public
    cap_add:
      - NET_ADMIN
    ports:
      - 9091:9091
    logging:
      driver: json-file
      options:
        max-size: 10m
    volumes:
      - nfs-transmission:/data
    environment:
#      - UFW_ALLOW_GW_NET=false
      - OPENVPN_CONFIG=nl.protonvpn.udp
      - OPENVPN_PROVIDER=PROTONVPN
      - OPENVPN_USERNAME=${VPNUSER}
      - OPENVPN_PASSWORD=${VPNPASS}
      - TZ=Europe/Paris
      - LOCAL_NETWORK=192.168.2.0/24
#      - OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60
#      - TRANSMISSION_CACHE_SIZE_MB=32
#      - TRANSMISSION_WEB_UI=transmission-web-control # OPTIONAL - just a different UI
#      - TRANSMISSION_PREFETCH_ENABLED=false
#      - TRANSMISSION_RPC_AUTHENTICATION_REQUIRED=true
#      - TRANSMISSION_DOWNLOAD_QUEUE_SIZE=100
#      - TRANSMISSION_MAX_PEERS_GLOBAL=3000
#      - TRANSMISSION_PEER_LIMIT_GLOBAL=3000
#      - TRANSMISSION_PEER_LIMIT_PER_TORRENT=300
#      - TRANSMISSION_DOWNLOAD_DIR=/completed
#      - TRANSMISSION_INCOMPLETE_DIR=/incomplete
#      - TRANSMISSION_RATIO_LIMIT=${RATIO_LIMIT}
#      - TRANSMISSION_RATIO_LIMIT_ENABLED=${RATIO_ENABLED}
#      - HEALTH_CHECK_HOST=google.com
#      - TRANSMISSION_RPC_USERNAME=${TRANSMISSION_RPC_USERNAME}
#      - TRANSMISSION_RPC_PASSWORD=${TRANSMISSION_RPC_PASSWORD}
#      - PUID=${PUID}
#      - PGID=${PGID}
#      - TRANSMISSION_RPC_WHITELIST_ENABLED=false
#      - WEBPROXY_ENABLED=false
#      - WEBPROXY_PORT=8888
    labels:
      - traefik.http.services.transmission.loadbalancer.server.port=9091
      - traefik.enable=true
      - traefik.docker.network=traefik-public
      - traefik.http.routers.transmission.rule=Host(`transmission.mete0r.fr`)
      - traefik.http.routers.transmission.tls=true
      - traefik.http.routers.transmission.tls.certresolver=default

networks:
  traefik-public:
    name: traefik-public


volumes:
  nfs-transmission:
    driver_opts:
      type: nfs
      o: addr=192.168.2.23,vers=4.1,nconnect=4,sec=sys,sync,rsize=131072,wsize=131072,nouser,soft,noatime,auto,retrans=2,rw,dev,exec
      device: :/volume4/Medias-HMS/transmission