version: '3'
services:
  netdata:
    image: netdata/netdata
    restart: always
    ports:
      - "19999:19999"
    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor:unconfined
    networks:
      - traefik-public
    volumes:
      - /etc/passwd:/host/etc/passwd:ro
      - /etc/group:/host/etc/group:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
    environment:
      - PGID=998
    labels:

      - traefik.enable=true
      - traefik.http.routers.netdata.rule=Host(`server.mete0r.fr`)
      - traefik.http.routers.netdata.tls=true
      - traefik.http.routers.netdata.tls.certresolver=default
networks:
  traefik-public:
    external: true